$FirebaseSDKVersion = '6.27.1'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'WitnessApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'WitnessAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # post_install do |pi|
  #   pi.pods_project.targets.each do |t|
  #     t.build_configurations.each do |config|
  #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  #     end
  #   end
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end


target 'WitnessApp-tvOS' do
  # Pods for WitnessApp-tvOS

  target 'WitnessApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
